# SETTINGS {{{

set -g default-terminal "screen-256color"
set -g base-index 1
set -g pane-base-index 1
set -g bell-action none
set -g display-time 3000
setw -g mode-keys vi
setw -g monitor-activity on

# Status
set -g status-position top
set -g status-right "W:#(cat /proc/net/wireless | grep wlp0s20f3 | awk '{gsub(/[^0-9]/,\"\",$3);print $3}')% E: #(head -c1 /sys/class/power_supply/BAT0/status)#(cat /sys/class/power_supply/BAT0/capacity) %a %d/%m/%y %H:%M"

# Colors
set -g status-style fg=colour136,bg=colour233,underscore
set -g pane-border-style fg=colour136
set -g pane-active-border-style fg=colour136
set -g message-style fg=colour233,bg=colour136
set -g window-status-current-style fg=colour233,bg=colour136
set -g window-status-style fg=colour136,bg=colour233
set -g window-status-activity-style fg=colour233,bg=1
set -s escape-time 0

# }}}

# Keybindings {{{ 

# Prefix
unbind C-b
set -g prefix M-`
bind M-` send-prefix

# Command
bind -n M-\: command-prompt

# Signals
bind -n M-z run "kill -s USR1 #{pane_pid}"
bind -n C-M-z run "kill -s USR2 #{pane_pid}"

# Panes
#bind -n M-w new-window -c "#{pane_current_path}"
bind -n M-w last-pane
bind -n M-t new-window -c "#{pane_current_path}"
bind -n M-s split-window -c "#{pane_current_path}"
bind -n M-v split-window -h -c "#{pane_current_path}"
bind -n M-\\ split-window -h -c "#{pane_current_path}"
bind -n M-\' split-window -c "#{pane_current_path}"
bind -n M-q kill-pane

# Motion
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

bind -n M-H swap-pane -D
bind -n M-J select-window -p
bind -n M-K select-window -n
bind -n M-L swap-pane -U

bind -n M-[ select-window -p
bind -n M-] select-window -n
bind -n M-^ last-window
bind -n M-` last-window
bind -n M-a last-window

# Windows 
bind -n M-1 select-window -t :1
bind -n M-2 select-window -t :2
bind -n M-3 select-window -t :3
bind -n M-4 select-window -t :4
bind -n M-5 select-window -t :5
bind -n M-6 select-window -t :6
bind -n M-7 select-window -t :7
bind -n M-8 select-window -t :8
bind -n M-9 select-window -t :9
bind -n M-0 select-window -t :10

# Resizing
bind -n M-, resize-pane -L 3
bind -n M-. resize-pane -R 3
bind -n M-- resize-pane -D 3
bind -n M-= resize-pane -U 3
bind -n M-< resize-pane -L 20
bind -n M-> resize-pane -R 20
bind -n M-_ resize-pane -D 20
bind -n M-+ resize-pane -U 20
#bind -n M-\\ resize-pane -x 100

# Copying
bind -n M-y copy-mode
bind -n M-Y choose-buffer "run \"tmux save-buffer -b %% - | wl-copy\""
bind -n M-o run "tmux set-buffer \"$(wl-paste)\"; tmux paste-buffer"
bind -n M-O choose-buffer 'paste-buffer -b %%'
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "tmux save-buffer - | wl-copy"
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi C-c send-keys -X clear-selection
bind -T copy-mode-vi Space send-keys -X page-down

# }}}
